config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'

  get '/users/index'
  get '/users/register'
  get '/users/edit'

  post '/users/register'
  patch '/users/update' => 'users#update'
  
  get '/organizations/index'
  post '/organizations/create'
  get '/organizations/destroy'
  get '/organizations/:id' => 'organizations#show'

  get '/plans/create'
  post '/plans/create'
  post '/plans/destroy'

  post '/session' => 'sessions#create'
  get '/sessions/destroy'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
  has_many :plans, dependent: :destroy
  validates :name, presence: :true, length: {minimum: 6} 
  validates :description, presence: :true, length: {minimum: 11}
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :organizations
	has_many :plans
	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name, :last_name, presence: :true, length: { within: 2..20 }
	validates :email, presence: true, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }


	def has_password?(submitted_password)
		self.password == submitted_password
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  
    def index
    	if session[:user_id].nil?
        	redirect_to users_index_path
    	else
    		@user = User.find(session[:user_id])
    		@orgs = Organization.all
    		@org = Organization.new
        	@members = Plan.select("plans.*, users.*").joins("LEFT JOIN users ON users.id = plans.user_id")
        	@plans = User.find(session[:user_id]).plans
        	@memberCount = 0
    	end
    end

    def show
    	@org = Organization.select("organizations.*, users.*").joins("LEFT JOIN users ON users.id = organizations.user_id").where("organizations.id = ?", params[:id]).first
  		@org[:id] = params[:id]
  		@members = Plan.select("plans.*, users.*").joins("LEFT JOIN users ON users.id = plans.user_id").where("plans.organization_id = ?", params[:id].to_i)
    end

    def create
    	@org = Organization.new(name: params[:name], description: params[:description], user_id: params[:user_id])
  		@org[:user_id] = @org[:user_id].to_i
  		if @org.save
  			redirect_to plans_create_path(user_id: @org.user_id, organization_id: @org.id)
  		else
  			flash[:errors] = @org.errors.full_messages
  			redirect_to organizations_index_path
  		end
    end

    def destroy
    	@org = Organization.find(params[:id].to_i)
    	if @org.destroy
    		redirect_to organizations_index_path
    	else
    		flash[:errors] = @org.errors.full_messages
    		redirect_to organizations_index_path
    	end
    end

    # private
    # 	def org_params
    # 		params.require(:organization).permit(:name, :description, :user_id)
    # 	end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
 	
 	def create
        @plan = Plan.where("user_id = ? AND organization_id = ?", params[:user_id].to_i, params[:organization_id].to_i)
        if @plan.empty?  
    	   @plan = Plan.new(user_id: params[:user_id].to_i, organization_id: params[:organization_id].to_i)
            if @plan.save
  			   redirect_to "/organizations/#{@plan.organization_id}"
  		    else
  			   flash[:plan_errors] = @plan.errors.full_messages
  			   redirect_to "/organizations/#{@plan.organization_id}"
  		    end
        else
            redirect_to "/organizations/#{@plan.organization_id}"
        end
    end

    def destroy
    	@plan = Plan.where(user: User.find(params[:user_id].to_i), organization: Organization.find(params[:organization_id].to_i)).first
    	if @plan.destroy
      		redirect_to "/organizations/#{@plan.organization_id}"
    	else
      		flash[:destroy_errors] = @plan.errors.full_messages
      		redirect_to "/organizations/#{@plan.organization_id}"
    	end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
		user = User.authenticate(params[:session][:email], params[:session][:password])
  		if user.nil?
  			flash[:error] = "Could not find a user with that email and password combination"
  			redirect_to users_index_path
  		else
  			session[:user_id] = user.id
  			redirect_to organizations_index_path user
  		end
	end

	def destroy
		session[:user_id] = nil
   		flash[:message] = 'You have successfully logged out'
  		redirect_to users_index_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
  		if !session[:user_id].nil?
        	redirect_to organizations_index_path
        end
    	@user = User.new
  	end

  	def register
  		@user = User.create(user_params)
    	if @user.save
    		session[:user_id] = @user.id
    		redirect_to organizations_index_path
    	else
    		flash[:errors] = @user.errors.full_messages
    		redirect_to users_index_path
    	end
  	end

 	def edit
 		@user = User.find(session[:user_id])
  	end

  	def update
  		@user = User.find(session[:user_id])
        if @user.update_attributes(user_params)
            redirect_to organizations_index_path
        else  
            flash[:errors] = @user.errors.full_messages
            redirect_to "/users/edit"
        end
  	end

  	private
    	def user_params
    		params.require(:user).permit(:first_name, :last_name, :email, :password)
    	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organizations/index.html.erb
<h1>Hi <%= @user.first_name + " " + @user.last_name + "!"%></h1>  
<h2><%= link_to 'Edit My Profile', users_edit_path %> | <%= link_to 'Logout', sessions_destroy_path %></h2>


<% if !@orgs.empty? %>
	<div id="orgs">	
		<h2>Here are the Organizations you may join:</h2>
		<% @orgs.each do |org|
			if org.user_id == session[:user_id] %>
				<h3><%= link_to org.name, '/organizations/'+ org.id.to_s %> | <%= link_to '(Delete Event)', organizations_destroy_path(:id => org.id) %></h3>
			<% else %>
				<h3><%= link_to org.name, '/organizations/'+ org.id.to_s %></h3>
			<% end %>
			<% if !(@members.empty?)
				@memberCount = 0
				@members.each do |member|
					if member.organization_id == org.id
						(@memberCount += 1)
					end
				end
			end %>
			<h4 class="indent">Members:<%= @memberCount %></h4>
			<h4 class="indent"><%= org.description %></h4>
		<% end %>
	</div>
<% end %>

<h2>Create a new Organization</h2>
<% if !flash[:errors].nil?
	flash[:errors].each do |error| %>
		<h4><%= error %></h4>
	<% end %>
<% end %>
<div id="form">	
	<form action="/organizations/create" id="disc" method="post">
		<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden"/>
		<input type="hidden" name="user_id" value="<%= session[:user_id] %>">
		<label>Organization Name:</label>
			<input type="text" name="name">
		<label>Description:</label>
			<textarea name="description" cols="30" rows="10"></textarea>
		<input id=box type="Submit" value="Create">
	</form>
</div>

app/views/organizations/show.html.erb
<h4><%= link_to "Dashboard", organizations_index_path %> | <%= link_to "Logout", sessions_destroy_path %></h4>

<% if !flash[:plan_errors].nil?
	flash[:plan_errors].each do |error| %>
	<h3><%= error %></h3>
	<% end %>
<% end %>

<%  if !(@members.empty?) 
	@members.each do |member|
		if member.user_id == session[:user_id] && member.organization_id == @org.id
			@status = button_to 'Leave Group', plans_destroy_path(:user_id => session[:user_id], :organization_id => @org.id)
			break
		else
			@status = button_to "Join Group", plans_create_path(:user_id => session[:user_id], :organization_id => @org.id)
		end
	end
else
	@status = button_to "Join Group", plans_create_path(:user_id => session[:user_id], :organization_id => @org.id)
end %>
<h2><%= @org.name %><%= @status %></h2>
<h4><%= @org.description %></h4>

<h3>Created By: <%= @org.first_name + " " + @org.last_name %></h3>
<h4>Members:</h4>
<% @members.each do |member| %>
	<h5><%= member.first_name + " " + member.last_name %></h5>
<% end %>

app/views/plans/destroy.html.erb
<h1>Plans#destroy</h1>
<p>Find me in app/views/plans/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="row">
	<div class="col-md-6">
		<h1>Login</h1>
		<% if flash[:error] %>
			<div class="alert-danger"><%= flash[:error] %></div>
		<% end %>
		<%= simple_form_for(:session, url: session_path) do |f| %>
			<%= f.input :email %>
			<%= f.input :password %>
			<%= f.button :submit, 'Login', class: "btn btn-primary" %>
		<% end %>
	</div>
	<div>
		<p>==============================================================================</p>
	</div>
	<div class="col-md-6">
		<h1>Register</h1>
		<% if flash[:errors] %>
			<% flash[:errors].each do |error| %>
				<div class="alert-danger"><%= error %></div>
			<% end %>
		<% end %>
		<%= simple_form_for @user, url: users_register_path do |f| %>
			<%= f.input :first_name, required: false %>
			<%= f.input :last_name, required: false %>
			<%= f.input :email, required: false %>
			<%= f.input :password, required: false %>
			<%= f.button :submit, 'Register', class: "btn btn-primary" %>
		<% end %>	
	</div>
</div>

app/views/users/register.html.erb
<h1>Users#register</h1>
<p>Find me in app/views/users/register.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>